// AUTO-GENERATED by tools/gen_puzzles.mjs — do not edit by hand.
//
// A progressive set of "you play and win" Connect Four puzzles, easiest first.
// In every puzzle YOU are P1 (red) and it's your move; the opponent is P2 (yellow).
//   grid  — 42 chars, row-major top→bottom, left→right; '0' empty, '1' you, '2' opponent.
//   line  — the unique solution: [yourCol, oppReplyCol, yourCol, …]. The opponent's
//           replies are its best defence; every one of your moves in the line is the
//           *only* move that keeps the win, so any other move is simply wrong.
//   winIn — how many of your moves reach four-in-a-row against best defence.
// Provably correct — tools/test_puzzles.mjs re-solves each one from scratch.
export const PUZZLES = [
  { id: 1, tier: 'Warm-up', winIn: 1, grid: '000202102211210111212122111222122112121122', line: [0] },
  { id: 2, tier: 'Warm-up', winIn: 1, grid: '121000211102011210202212210122212112112122', line: [3] },
  { id: 3, tier: 'Warm-up', winIn: 1, grid: '000000022100001220012121202121211212111221', line: [4] },
  { id: 4, tier: 'Warm-up', winIn: 1, grid: '002010000202010220221021012101211121211221', line: [6] },
  { id: 5, tier: 'Warm-up', winIn: 1, grid: '010000002020202201020110121212212112112121', line: [2] },
  { id: 6, tier: 'Warm-up', winIn: 1, grid: '000000012200001120010221002012102101110222', line: [3] },
  { id: 7, tier: 'Warm-up', winIn: 1, grid: '000000000101000020220121022021112102122110', line: [1] },
  { id: 8, tier: 'Warm-up', winIn: 1, grid: '000100000020000012010202111020222101221121', line: [5] },
  { id: 9, tier: 'Sharp', winIn: 2, grid: '020200002010011101201120210221022211122121', line: [2, 2, 2] },
  { id: 10, tier: 'Sharp', winIn: 2, grid: '002010010102002010102202221210211211121122', line: [3, 3, 5] },
  { id: 11, tier: 'Sharp', winIn: 2, grid: '000012000001110020212021012121222112121221', line: [3, 3, 3] },
  { id: 12, tier: 'Sharp', winIn: 2, grid: '200000010102001010120122021221101221220121', line: [6, 3, 3] },
  { id: 13, tier: 'Sharp', winIn: 2, grid: '000010002202000210220012011012122211112121', line: [6, 3, 6] },
  { id: 14, tier: 'Sharp', winIn: 2, grid: '000002000002101000110200022220012211211211', line: [3, 3, 2] },
  { id: 15, tier: 'Sharp', winIn: 2, grid: '000000000002000110220022011002112122122111', line: [6, 3, 3] },
  { id: 16, tier: 'Sharp', winIn: 2, grid: '001002000200100020010001001022122211112221', line: [3, 3, 4] },
  { id: 17, tier: 'Tactician', winIn: 3, grid: '020210212011012122102121122121121122212112', line: [2, 2, 0, 5, 5] },
  { id: 18, tier: 'Tactician', winIn: 3, grid: '002220110111212021221102211212111221212122', line: [5, 1, 1, 1, 1] },
  { id: 19, tier: 'Tactician', winIn: 3, grid: '020110001012222102111220112221221221121211', line: [0, 5, 2, 2, 2] },
  { id: 20, tier: 'Tactician', winIn: 3, grid: '010010212002121100221220111221022211221121', line: [2, 2, 3, 3, 2] },
  { id: 21, tier: 'Tactician', winIn: 3, grid: '200001020002101100112220022111201122212112', line: [2, 3, 2, 3, 3] },
  { id: 22, tier: 'Tactician', winIn: 3, grid: '200000110002011200101110021222211222122112', line: [5, 2, 2, 3, 3] },
  { id: 23, tier: 'Tactician', winIn: 3, grid: '012000001101000120100021020221221122111222', line: [6, 5, 3, 3, 3] },
  { id: 24, tier: 'Sniper', winIn: 4, grid: '120020121001212100122120122111122122211122', line: [5, 3, 3, 3, 2, 2, 2] },
  { id: 25, tier: 'Sniper', winIn: 4, grid: '102210120122022022101101112110121221221212', line: [1, 1, 1, 1, 1, 5, 5] },
  { id: 26, tier: 'Sniper', winIn: 4, grid: '010022002011122101222210211212121211112221', line: [6, 0, 0, 3, 2, 2, 2] },
  { id: 27, tier: 'Sniper', winIn: 4, grid: '021001122200211120012221001221120112121221', line: [3, 3, 3, 3, 0, 4, 4] },
  { id: 28, tier: 'Sniper', winIn: 4, grid: '200021010002102100210122012021221102121112', line: [2, 3, 2, 3, 3, 3, 1] },
  { id: 29, tier: 'Sniper', winIn: 4, grid: '000000020001002000120100021021221211212112', line: [1, 2, 1, 1, 2, 3, 3] },
  { id: 30, tier: 'Sniper', winIn: 4, grid: '020000001000000200100012020112211222211121', line: [5, 6, 2, 3, 3, 3, 5] },
  { id: 31, tier: 'Grandmaster', winIn: 5, grid: '000202100010112022012111222122121112211122', line: [1, 2, 2, 1, 1, 0, 0, 4, 4] },
  { id: 32, tier: 'Grandmaster', winIn: 5, grid: '010201011020202201021112201221121221222111', line: [4, 4, 4, 4, 0, 6, 6, 2, 2] },
  { id: 33, tier: 'Grandmaster', winIn: 5, grid: '100120012022102101220110212022012201112112', line: [6, 1, 5, 6, 6, 6, 6, 2, 2] },
  { id: 34, tier: 'Grandmaster', winIn: 6, grid: '200020210011022002101120120212122121212111', line: [1, 3, 1, 2, 1, 5, 5, 5, 5, 2, 2] },
  { id: 35, tier: 'Grandmaster', winIn: 6, grid: '001020120101021010102202020120121112221122', line: [3, 3, 1, 1, 1, 1, 3, 5, 5, 3, 5] },
  { id: 36, tier: 'Grandmaster', winIn: 7, grid: '200001120000211000022202001111202122111221', line: [4, 2, 2, 2, 4, 4, 4, 1, 1, 1, 1, 3, 3] },
];
