// AUTO-GENERATED by tools/gen_tactics.mjs — do not edit by hand.
//
// The Tactics curriculum: eight ideas a player can actually learn, each with a
// short lesson the teacher walks you through and drills to try it on.
//   lesson — the teacher's pages. Each carries the position to show ('grid', 42
//            chars, row-major top→bottom; '0' empty, '1' you/red, '2' them/yellow)
//            and optionally squares ('marks'), whole columns ('cols') or rows
//            ('rows') to light up while it is on screen.
//   close  — what the teacher says once you have finished all of its drills.
//   drills — positions where YOU are red and to move. 'good' is the move the
//            tactic is about, and the solver has confirmed it is the ONLY move
//            that works, so anything else is a real mistake. 'show' is what the
//            teacher lights up once you have played it — the very squares the
//            tactic is about. 'follow' marks the drills where every reply leaves
//            you an immediate four, so the app can let you play the win out.
//            'values' is the solver's verdict on every column from your side
//            (> 0 wins, 0 draws, < 0 loses, null = full), so the app can accept
//            any move that comes to the same thing as the one being taught.
// Every position here was generated and proven by the exact solver, and
// tools/test_tactics.mjs re-proves all of it from scratch.
export const TACTICS = [
  {
    id: 'centre',
    name: 'Own the center',
    idea: 'The middle column sits on more fours than any other square on the board.',
    ask: 'Only one column keeps your win. Which?',
    why: 'The middle. Every line you want runs through it.',
    nudge: 'That hands the game back. Where do the most fours meet?',
    close: 'That is the middle. Take it early and your fours are already half-built.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Welcome. Geometry first. There are 69 ways to make four here. 51 of them run through the middle column.', cols: [3] },
      { grid: '000000000000000000000000000000000000000000', say: 'The edges barely matter — 15 each. These two middle squares sit on 13 fours apiece. A corner sits on 3.', marks: [[2, 3], [3, 3]] },
      { grid: '000000000001010000201022020201211022211121', say: 'So the middle decides games. Open there and you win. Open on the edge and you lose. Here, only the center holds it.' },
    ],
    drills: [
      { grid: '000000000001010000201022020201211022211121', good: [3], follow: false,
        show: [[2, 3]], values: [-11, -11, -11, 1, -11, -11, -11] },
      { grid: '000002001000100200020010021002001102121212', good: [3], follow: true,
        show: [[4, 2], [4, 6]], values: [-12, -12, -12, 11, -12, null, -12] },
      { grid: '000000000000001000001120010221201211220212', good: [3], follow: false,
        show: [[3, 5]], values: [-12, -12, -12, 3, -12, -12, -12] },
    ],
  },
  {
    id: 'fork',
    name: 'Two threats at once',
    idea: 'One threat gets blocked. Two open threats in one move cannot both be stopped.',
    ask: 'Find the move that makes two threats at once.',
    why: 'Two open winning squares. They block one. You take the other.',
    nudge: 'That makes one threat at most. They simply block it.',
    close: 'The fork is the engine of this game. Every other idea is a way to build one.',
    lesson: [
      { grid: '100010020202001210200222010011212011211221', say: 'A threat is an empty square that would give you four. One threat is polite. They just fill it.' },
      { grid: '100010020202001210200222110011212011211221', say: 'Two at once is a fork. They answer one. You take the other. That is how games are really won.', marks: [[1, 1], [2, 3]] },
      { grid: '100010020202001210200222010011212011211221', say: 'Your turn. One move here makes two.' },
    ],
    drills: [
      { grid: '100010020202001210200222010011212011211221', good: [3], follow: true,
        show: [[1, 1], [2, 3]], values: [null, -8, -8, 7, null, -8, -8] },
      { grid: '000000000000000000210210111012022202121210', good: [2], follow: true,
        show: [[2, 0], [3, 2]], values: [-12, -12, 11, -12, -12, -12, -12] },
      { grid: '000000000000000200010020202011122101122121', good: [3], follow: true,
        show: [[3, 2], [3, 4]], values: [-12, -12, -12, 11, -12, -12, -12] },
    ],
  },
  {
    id: 'seven',
    name: 'The seven',
    idea: 'One disc finishing two lines — three along a row, three down a diagonal.',
    ask: 'One move builds a row and a diagonal. Find it.',
    why: 'A row and a diagonal from one disc. That is the seven.',
    nudge: 'That points one way only. Find the disc that finishes two lines.',
    close: 'Look for sevens in your own games. Once you know the shape, you see it everywhere.',
    lesson: [
      { grid: '100000010000012000002110022112212222121112', say: 'The best disc belongs to two lines at once. Three along a row, three down a diagonal. The shape looks like a 7.' },
      { grid: '100000010000012000002111022112212222121112', say: 'Look what it asks for. One square for the row. A different one for the diagonal. Two lines, one disc.', marks: [[2, 1], [3, 3]] },
      { grid: '100000010000012000002110022112212222121112', say: 'Now find it. One move here starts both lines.' },
    ],
    drills: [
      { grid: '100000010000012000002110022112212222121112', good: [2], follow: true,
        show: [[2, 1], [3, 3]], values: [null, -8, 8, -9, -8, -8, -8] },
      { grid: '010000002002000100100022010001102222112112', good: [3], follow: true,
        show: [[2, 5], [4, 0]], values: [-11, null, -11, 10, -11, -11, -11] },
      { grid: '000010000002000002101000110200212021022112', good: [2], follow: false,
        show: [[2, 1], [3, 1], [3, 5]], values: [-5, -11, 9, -5, null, -5, -5] },
    ],
  },
  {
    id: 'tempo',
    name: 'Block and build',
    idea: 'A forced block need not be a wasted move. Block with a disc that threatens back.',
    ask: 'They have four next move. Deal with it.',
    why: 'Forced — but your block builds too. Now they must answer you.',
    nudge: 'They complete four next move. Everything but that block loses.',
    close: 'Never block emptily. A block that threatens back is an attack.',
    lesson: [
      { grid: '001000000200001010002121010122202021122121', say: 'Now the other side. They are one move from four. The square they need is marked. It has to be yours.', marks: [[4, 3]] },
      { grid: '001000000200001010002121010122212021122121', say: 'But a forced move can still build. This block makes a three of your own. Now they must answer you.', marks: [[2, 1]] },
      { grid: '001000000200001010002121010122202021122121', say: 'Block it. Then look at what your disc did on the way.' },
    ],
    drills: [
      { grid: '001000000200001010002121010122202021122121', good: [3], follow: false,
        show: [[2, 1]], values: [-10, -10, null, 1, -10, -10, -10] },
      { grid: '000000021000001210000212000012101002122102', good: [3], follow: false,
        show: [[4, 5]], values: [-12, -12, -12, 0, -12, -12, -12] },
      { grid: '000000000000000002000110120012011002122200', good: [5], follow: false,
        show: [[2, 2]], values: [-14, -14, -14, -14, -14, 2, -14] },
    ],
  },
  {
    id: 'poison',
    name: 'Poisoned squares',
    idea: 'A disc under one of their winning squares lifts them straight onto it.',
    ask: 'Most of these columns hand them the win. Find the one that does not.',
    why: 'Safe. The others lift them onto four, or lose a step later.',
    nudge: 'Look above each landing square. Your disc under their win hands it to them.',
    close: 'Before every drop, ask what square you are handing over. Two seconds. Whole games.',
    lesson: [
      { grid: '110020021001022201102210220112021111221212', say: 'Find their winning squares first. The empty ones that would give them four. These.', marks: [[2, 5], [3, 2]] },
      { grid: '110020021001022201102210220112021111221212', say: 'Now look underneath. Your disc lifts them onto the square above. Every marked column is poisoned.', cols: [2, 5] },
      { grid: '110020021001022201102210220112021111221212', say: 'Most of this board is a trap. One move keeps you alive. Only one.' },
    ],
    drills: [
      { grid: '110020021001022201102210220112021111221212', good: [3], follow: false,
        show: [[1, 2], [2, 2], [3, 5]], values: [null, null, -6, 2, null, -6, -2] },
      { grid: '002100000122000011102102210122122022111201', good: [0], follow: true,
        show: [[3, 1]], values: [7, -8, null, null, -5, -8, -5] },
      { grid: '020000201000010222001021100112121022122101', good: [2], follow: false,
        show: [], values: [-9, null, 3, -8, -9, -8, null] },
    ],
  },
  {
    id: 'stack',
    name: 'Stack your threats',
    idea: 'Two of your winning squares in one column, one directly above the other.',
    ask: 'Put two of your winning squares in one column, one above the other.',
    why: 'Stacked. Block the low one and their own disc carries you to the high one.',
    nudge: 'Not that. Find the column where your threats can sit on top of each other.',
    close: 'Two threats in one column, and their own move loses it. Nothing here is prettier.',
    lesson: [
      { grid: '000000001110000221002011220222121212112211', say: 'The prettiest idea in the game. Two of your winning squares in one column, one directly above the other.' },
      { grid: '000000001110000221002011221222121212112211', say: 'They cannot block the low one without playing it. That lifts you to the high one. Block below, lose above.', marks: [[1, 4], [2, 4]] },
      { grid: '000000001110000221002011220222121212112211', say: 'Find the move that stacks them.' },
    ],
    drills: [
      { grid: '000000001110000221002011220222121212112211', good: [5], follow: true,
        show: [[1, 4], [2, 4]], values: [-8, -8, -8, -8, -8, 7, -8] },
      { grid: '000000000000100100220020012011001202212112', good: [3], follow: true,
        show: [[3, 2], [4, 2]], values: [-2, -2, -2, 11, -4, -4, -3] },
      { grid: '000001000000200000010002001200101122210122', good: [6], follow: true,
        show: [[4, 3], [5, 3]], values: [-13, -13, -13, -13, -13, null, 12] },
    ],
  },
  {
    id: 'parity',
    name: 'Odd rows are yours',
    idea: 'Rows fill in order, so a threat on the right row is the one that gets collected.',
    ask: 'Two moves look alike. Only one lands on your row. Find it.',
    why: 'That one. Your winning square is on an odd row, so it falls to you.',
    nudge: 'Wrong row. They get to fill that square, not you.',
    close: 'Counting rows is dull, and it wins games. Start counting around move ten.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Count the rows from the bottom: 1 to 6. Discs fill them in order. The board holds 42 squares — an even number.', rows: [5, 3, 1] },
      { grid: '000000000000000000000000000000000000000000', say: 'So the rows split between you. You moved first, so the odd rows tend to fall to you. The even rows fall to them.', rows: [5, 3, 1] },
      { grid: '201001010200202010010101021012201202210221', say: 'Here two moves look alike. Only one puts your threat on your row. Count. Do not guess.' },
    ],
    drills: [
      { grid: '201001010200202010010101021012201202210221', good: [1], follow: false,
        show: [[1, 3], [3, 3]], values: [null, 5, null, -2, -8, null, -8] },
      { grid: '001000002100000110010012002021200202212121', good: [3], follow: false,
        show: [[3, 4]], values: [-9, -9, null, 4, 0, -9, -9] },
      { grid: '100000020000001000000202000010101001220221', good: [3], follow: false,
        show: [[3, 1]], values: [null, -14, -14, 4, -14, -14, -14] },
    ],
  },
  {
    id: 'defuse',
    name: 'Kill the fork early',
    idea: 'Everything you have learned, they can use. Take the double threat away a move early.',
    ask: 'They are one move from a double threat. Take it away.',
    why: 'Defused. The square their fork needed is yours.',
    nudge: 'Too slow. They fork you, and two open threats cannot both be blocked.',
    close: 'That is the craft: build your fork, and see theirs coming. Go and play.',
    lesson: [
      { grid: '000000200020020001001002200212112112111212', say: 'Last idea, and it keeps you alive. Everything I taught you, they can play too. So ask what their next move does.' },
      { grid: '000000200020020001001002200212112112111212', say: 'If they reach the marked column they fork you. You know how that ends. It is their move to lose.', marks: [[3, 1], [3, 4]] },
      { grid: '000000200020020001001002200212112112111212', say: 'Take it away from them.' },
    ],
    drills: [
      { grid: '000000200020020001001002200212112112111212', good: [4], follow: false,
        show: [[1, 2], [2, 5]], values: [-9, -9, -9, -9, 0, -7, null] },
      { grid: '020000001100000210000112220021212001121122', good: [3], follow: false,
        show: [], values: [-9, null, -9, 0, -9, -10, -9] },
      { grid: '000000002000000100000020200111211022211221', good: [2], follow: false,
        show: [[1, 0]], values: [-11, -11, 2, -11, -12, -11, -11] },
    ],
  },
];
