// AUTO-GENERATED by tools/gen_tactics.mjs — do not edit by hand.
//
// The Tactics curriculum: ten ideas a player can actually learn, each with a
// short lesson the teacher walks you through and drills to try it on.
//   lesson — the teacher's pages. Each carries the position to show ('grid', 42
//            chars, row-major top→bottom; '0' empty, '1' you/red, '2' them/yellow)
//            and optionally squares ('marks'), whole columns ('cols') or rows
//            ('rows') to light up while it is on screen. A page with 'play' is a
//            demonstration: those columns are dropped in turn (you, them, you) so
//            the teacher shows the idea working instead of describing it.
//   close  — what the teacher says once you have finished all of its drills.
//   drills — positions where YOU are red and to move. 'good' is the move the
//            tactic is about, and the solver has confirmed it is the ONLY move
//            that works, so anything else is a real mistake. 'show' is what the
//            teacher lights up once you have played it — the very squares the
//            tactic is about. 'follow' marks the drills where every reply leaves
//            you an immediate four, so the app can let you play the win out, and
//            'convert' marks the last drill of a tactic, where you carry the idea
//            through to the four yourself over 'winIn' moves against live defence.
//            'values' is the solver's verdict on every column from your side
//            (> 0 wins, 0 draws, < 0 loses, null = full), so the app can accept
//            any move that comes to the same thing as the one being taught.
// Every position here was generated and proven by the exact solver, and
// tools/test_tactics.mjs re-proves all of it from scratch.
export const TACTICS = [
  {
    id: 'centre',
    name: 'Own the center',
    idea: 'The middle column sits on more fours than any other square on the board.',
    ask: 'Only one column keeps your win. Which?',
    why: 'The middle. Every line you want runs through it.',
    nudge: 'That hands the game back. Where do the most fours meet?',
    close: 'That is the middle. Take it early and your fours are already half-built.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Welcome. Geometry first. There are 69 ways to make four here. 51 of them run through the middle column.', cols: [3] },
      { grid: '000000000000000000000000000000000000000000', say: 'The edges barely matter — 15 each. These two middle squares sit on 13 fours apiece. A corner sits on 3.', marks: [[2, 3], [3, 3]] },
      { grid: '000000000000000000000000212001222112111212', say: 'So the middle decides games. Open there and you win. Open on the edge and you lose. Here, only the center holds it.' },
    ],
    drills: [
      { grid: '000000000000000000000000212001222112111212', good: [3], follow: false,
        show: [[1, 2]], values: [-10, -10, -2, 1, -2, -4, -6] },
      { grid: '000000000000000000100120210121122121222112', good: [3], follow: false,
        show: [[1, 2], [3, 2]], values: [-11, -11, -11, 9, -11, -11, -11] },
      { grid: '002000000100000010200011020022211001211202', good: [3], follow: true,
        show: [[1, 1], [2, 3], [3, 0], [5, 5]], values: [-12, -12, null, 11, -12, -12, -12] },
      { grid: '001000000200201210010211002022201202112110', good: [3], follow: true, convert: true, winIn: 2,
        show: [[3, 4]], values: [-10, -10, null, 9, -10, -10, -10] },
    ],
  },
  {
    id: 'fork',
    name: 'Two threats at once',
    idea: 'One threat gets blocked. Two open threats in one move cannot both be stopped.',
    ask: 'Find the move that makes two threats at once.',
    why: 'Two open winning squares. They block one. You take the other.',
    nudge: 'That makes one threat at most. They simply block it.',
    close: 'The fork is the engine of this game. Every other idea is a way to build one.',
    lesson: [
      { grid: '000000002020000102000020101001122201211210', say: 'A threat is an empty square that would give you four. One threat is polite. They just fill it.' },
      { grid: '000000002020000102000020101001122201211210', say: 'Two at once is a fork. They answer one. You take the other. That is how games are really won.', play: [2, 2, 4], marks: [[2, 2], [3, 4]] },
      { grid: '000000002020000102000020101001122201211210', say: 'Your turn. One move here makes two.' },
    ],
    drills: [
      { grid: '000000002020000102000020101001122201211210', good: [2], follow: true,
        show: [[2, 2], [3, 4]], values: [-11, -11, 11, -11, -4, -11, -12] },
      { grid: '200000010010001002200200220010011022112211', good: [2], follow: true,
        show: [[4, 1], [4, 5]], values: [null, -4, 10, -5, -7, -8, -7] },
      { grid: '000020001002200100110020212101012112122212', good: [6], follow: true,
        show: [[1, 6], [2, 3]], values: [-9, -9, -9, -9, null, -9, 8] },
      { grid: '000000000000000200210021022121211121212211', good: [3], follow: true, convert: true, winIn: 2,
        show: [[2, 2], [2, 3]], values: [-10, -10, -10, 9, -10, -10, -10] },
    ],
  },
  {
    id: 'seven',
    name: 'The seven',
    idea: 'One disc finishing two lines — three along a row, three down a diagonal.',
    ask: 'One move builds a row and a diagonal. Find it.',
    why: 'A row and a diagonal from one disc. That is the seven.',
    nudge: 'That points one way only. Find the disc that finishes two lines.',
    close: 'Look for sevens in your own games. Once you know the shape, you see it everywhere.',
    lesson: [
      { grid: '001000000200201010011201201220120122122121', say: 'The best disc belongs to two lines at once. Three along a row, three down a diagonal. The shape looks like a 7.' },
      { grid: '001000000200201010011201201220120122122121', say: 'Look what it asks for. One square for the row. A different one for the diagonal. Two lines, one disc.', play: [3], marks: [[2, 1], [2, 4], [3, 4]] },
      { grid: '001000000200201010011201201220120122122121', say: 'Now find it. One move here starts both lines.' },
    ],
    drills: [
      { grid: '001000000200201010011201201220120122122121', good: [3], follow: false,
        show: [[2, 1], [2, 4], [3, 4]], values: [-9, -9, null, 7, -9, -9, -9] },
      { grid: '000000000120002122000221100012221122111211', good: [5], follow: true,
        show: [[2, 5], [2, 6], [3, 4]], values: [-2, -2, -2, -2, 0, 8, -2] },
      { grid: '000000000000002101000212200112211122221112', good: [2], follow: false,
        show: [[1, 3], [2, 4]], values: [-10, -10, 8, -10, -10, -10, -10] },
      { grid: '021000002201020110201012210112211022112221', good: [3], follow: true, convert: true, winIn: 2,
        show: [[2, 0], [4, 5]], values: [-7, null, null, 6, -7, -7, -7] },
    ],
  },
  {
    id: 'tempo',
    name: 'Block and build',
    idea: 'A forced block need not be a wasted move. Block with a disc that threatens back.',
    ask: 'They have four next move. Deal with it.',
    why: 'Forced — but your block builds too. Now they must answer you.',
    nudge: 'They complete four next move. Everything but that block loses.',
    close: 'Never block emptily. A block that threatens back is an attack.',
    lesson: [
      { grid: '000000010000002000000100022211221112211212', say: 'Now the other side. They are one move from four. The square they need is marked. It has to be yours.', marks: [[3, 3]] },
      { grid: '000000010000002000000100022211221112211212', say: 'But a forced move can still build. This block makes a three of your own. Now they must answer you.', play: [3], marks: [[2, 2]] },
      { grid: '000000010000002000000100022211221112211212', say: 'Block it. Then look at what your disc did on the way.' },
    ],
    drills: [
      { grid: '000000010000002000000100022211221112211212', good: [3], follow: false,
        show: [[2, 2]], values: [-11, -11, -11, 2, -11, -11, -11] },
      { grid: '000000000010000021102102220120112122021112', good: [5], follow: false,
        show: [[0, 2], [2, 5]], values: [-10, -10, -10, -10, -10, 3, -10] },
      { grid: '000000000210000021000002201102110222111212', good: [2], follow: false,
        show: [[2, 4]], values: [-11, -11, 0, -11, -11, -11, -11] },
    ],
  },
  {
    id: 'poison',
    name: 'Poisoned squares',
    idea: 'A disc under one of their winning squares lifts them straight onto it.',
    ask: 'Most of these columns hand them the win. Find the one that does not.',
    why: 'Safe. The others lift them onto four, or lose a step later.',
    nudge: 'Look above each landing square. Your disc under their win hands it to them.',
    close: 'Before every drop, ask what square you are handing over. Two seconds. Whole games.',
    lesson: [
      { grid: '000001000100200122010022122012221111112212', say: 'Find their winning squares first. The empty ones that would give them four. These.', marks: [[1, 4], [2, 0]] },
      { grid: '000001000100200122010022122012221111112212', say: 'Now look underneath. Your disc lifts them onto the square above. Every marked column is poisoned.', cols: [0, 4] },
      { grid: '000001000100200122010022122012221111112212', say: 'Most of this board is a trap. One move keeps you alive. Only one.' },
    ],
    drills: [
      { grid: '000001000100200122010022122012221111112212', good: [3], follow: false,
        show: [], values: [-8, -6, -5, 0, -8, null, -4] },
      { grid: '100000021000001120000122120021121101221222', good: [2], follow: false,
        show: [[0, 3]], values: [null, -2, 0, -9, -7, -9, -7] },
      { grid: '001002000120100021020001101120120122221212', good: [6], follow: true,
        show: [[4, 4]], values: [-5, -9, null, -5, -9, null, 8] },
    ],
  },
  {
    id: 'stack',
    name: 'Stack your threats',
    idea: 'Two of your winning squares in one column, one directly above the other.',
    ask: 'Put two of your winning squares in one column, one above the other.',
    why: 'Stacked. Block the low one and their own disc carries you to the high one.',
    nudge: 'Not that. Find the column where your threats can sit on top of each other.',
    close: 'Two threats in one column, and their own move loses it. Nothing here is prettier.',
    lesson: [
      { grid: '020000101000020100002020022122001121211121', say: 'The prettiest idea in the game. Two of your winning squares in one column, one directly above the other.' },
      { grid: '020000101000020100002020022122001121211121', say: 'They cannot block the low one without playing it. That lifts you to the high one. Block below, lose above.', play: [3, 2, 2], marks: [[3, 2], [4, 2]] },
      { grid: '020000101000020100002020022122001121211121', say: 'Find the move that stacks them.' },
    ],
    drills: [
      { grid: '020000101000020100002020022122001121211121', good: [3], follow: true,
        show: [[3, 2], [4, 2]], values: [-9, null, -2, 9, -9, -2, null] },
      { grid: '000000000000000000020221001221121111122212', good: [4], follow: true,
        show: [[2, 3], [3, 3]], values: [-11, -11, -11, -11, 10, -11, -11] },
      { grid: '100000010000002210201111012221201222211221', good: [5], follow: true,
        show: [[3, 3], [4, 3]], values: [null, -8, -8, -8, -8, 7, -8] },
      { grid: '002000000200100010021001002111220221112212', good: [4], follow: true, convert: true, winIn: 2,
        show: [[2, 3], [3, 3]], values: [-10, -10, null, -10, 9, -10, -10] },
    ],
  },
  {
    id: 'parity',
    name: 'Odd rows are yours',
    idea: 'Rows fill in order, so a threat on the right row is the one that gets collected.',
    ask: 'Two moves look alike. Only one lands on your row. Find it.',
    why: 'That one. Your winning square is on an odd row, so it falls to you.',
    nudge: 'Wrong row. They get to fill that square, not you.',
    close: 'Counting rows is dull, and it wins games. Start counting around move ten.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Count the rows from the bottom: 1 to 6. Discs fill them in order. The board holds 42 squares — an even number.', rows: [5, 3, 1] },
      { grid: '000000000000000000000000000000000000000000', say: 'So the rows split between you. You moved first, so the odd rows tend to fall to you. The even rows fall to them.', rows: [5, 3, 1] },
      { grid: '000020001001000100100020010202002021222111', say: 'Here two moves look alike. Only one puts your threat on your row. Count. Do not guess.' },
    ],
    drills: [
      { grid: '000020001001000100100020010202002021222111', good: [3], follow: false,
        show: [[3, 2]], values: [-11, -11, -10, 3, null, -11, -11] },
      { grid: '010000001000000200201211020211201022221112', good: [2], follow: false,
        show: [[1, 3], [3, 3]], values: [-7, null, 2, -10, -7, -7, -7] },
      { grid: '000000000000000000000200010020121212011212', good: [0], follow: false,
        show: [[3, 1]], values: [4, -14, -14, -14, -14, -14, -14] },
      { grid: '101000011102001220100221010221122012212122', good: [3], follow: false, convert: true, winIn: 3,
        show: [[1, 5], [3, 5]], values: [null, -7, null, 5, -7, -7, -7] },
    ],
  },
  {
    id: 'defuse',
    name: 'Kill the fork early',
    idea: 'Everything you have learned, they can use. Take the double threat away a move early.',
    ask: 'They are one move from a double threat. Take it away.',
    why: 'Defused. The square their fork needed is yours.',
    nudge: 'Too slow. They fork you, and two open threats cannot both be blocked.',
    close: 'That is the craft: build your fork, and see theirs coming. Go and play.',
    lesson: [
      { grid: '000000200101010020102001220222212011121112', say: 'Last idea, and it keeps you alive. Everything I taught you, they can play too. So ask what their next move does.' },
      { grid: '000000200101010020102001220222212011121112', say: 'If they reach the marked column they fork you. You know how that ends. It is their move to lose.', marks: [[4, 5]] },
      { grid: '000000200101010020102001220222212011121112', say: 'Take it away from them.' },
    ],
    drills: [
      { grid: '000000200101010020102001220222212011121112', good: [3], follow: false,
        show: [[0, 5]], values: [-8, -7, -8, 0, -8, -9, null] },
      { grid: '000000020000001200000210100012020202112110', good: [4], follow: false,
        show: [[2, 2]], values: [-12, -12, -13, -12, 0, -12, -12] },
      { grid: '000000000000000000000020200001211201222111', good: [2], follow: true,
        show: [[2, 1], [2, 3]], values: [-13, -13, 13, -13, -14, -13, -13] },
    ],
  },
  {
    id: 'above',
    name: 'Sit above their threat',
    idea: 'A winning square of yours directly above one of theirs kills it stone dead.',
    ask: 'One move leaves their threat unplayable. Find it.',
    why: 'Now their square is poison to them — taking it hands you the one above.',
    nudge: 'Their threat is still live. Find the move that makes taking it lose.',
    close: 'You do not always have to block a threat. Sometimes you just make it unusable.',
    lesson: [
      { grid: '201000010200022010011102202220120121121211', say: 'They have a winning square waiting. You could block it — or you could make it worthless.', marks: [[2, 1], [3, 4]] },
      { grid: '201000010200022010011102202220120121121211', say: 'Put a winning square of yours directly above theirs. Now taking theirs lifts you onto yours.', play: [3], marks: [[2, 4]] },
      { grid: '201000010200022010011102202220120121121211', say: 'Their threat is still on the board and they can never use it. Find that move.' },
    ],
    drills: [
      { grid: '201000010200022010011102202220120121121211', good: [3], follow: false,
        show: [[2, 4]], values: [null, -2, null, 2, -8, -2, -2] },
      { grid: '000000000200001010002202010120202011012121', good: [3], follow: false,
        show: [[2, 5]], values: [-11, -11, -11, 0, -11, -12, -11] },
      { grid: '000000100001022000201211022111122122221112', good: [5], follow: false,
        show: [[0, 3]], values: [-8, -8, -8, -8, -8, 0, null] },
    ],
  },
  {
    id: 'claimeven',
    name: 'Even rows, second player',
    idea: 'When you move second the even rows fall to you — the mirror of odd-row parity.',
    ask: 'You moved second here. Which move puts your threat on a row you will get?',
    why: 'That one. An even row, and you are the one who fills it.',
    nudge: 'Odd rows belong to whoever opened. That threat is theirs to fill, not yours.',
    close: 'Moving second is not a handicap. Take the even rows and let them run out of moves.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'You did not open this game. They did. That changes which rows are yours.', rows: [4, 2, 0] },
      { grid: '000000000000000000000000000000000000000000', say: 'The odd rows fall to the player who opened. The even rows — 2, 4 and 6, lit here — fall to you.', rows: [4, 2, 0] },
      { grid: '000000000000000021020201201010120112212212', say: 'So build on the even rows and let them run out of safe moves. Find the move.' },
    ],
    drills: [
      { grid: '000000000000000021020201201010120112212212', good: [3], follow: false,
        show: [[2, 4]], values: [-1, 0, 0, 6, 0, 0, -1] },
      { grid: '000100000020020001001200120211221122122121', good: [4], follow: false,
        show: [[2, 5]], values: [-8, -3, -8, null, 3, -9, -8] },
      { grid: '000002000000101021020201201010211122212212', good: [0], follow: false,
        show: [[2, 1]], values: [2, 0, 0, -6, -9, null, 0] },
      { grid: '000000001200012220002221010211202211121211', good: [3], follow: false, convert: true, winIn: 4,
        show: [[2, 5]], values: [-8, -8, -8, 6, -8, -8, -8] },
    ],
  },
];
