// AUTO-GENERATED by tools/gen_tactics.mjs — do not edit by hand.
//
// The Tactics curriculum: eight ideas a player can actually learn, each with a
// short lesson the teacher walks you through and drills to try it on.
//   lesson — the teacher's pages. Each carries the position to show ('grid', 42
//            chars, row-major top→bottom; '0' empty, '1' you/red, '2' them/yellow)
//            and optionally squares ('marks'), whole columns ('cols') or rows
//            ('rows') to light up while it is on screen.
//   close  — what the teacher says once you have finished all of its drills.
//   drills — positions where YOU are red and to move. 'good' is the move the
//            tactic is about, and the solver has confirmed it is the ONLY move
//            that works, so anything else is a real mistake. 'show' is what the
//            teacher lights up once you have played it — the very squares the
//            tactic is about. 'follow' marks the drills where every reply leaves
//            you an immediate four, so the app can let you play the win out.
// Every position here was generated and proven by the exact solver, and
// tools/test_tactics.mjs re-proves all of it from scratch.
export const TACTICS = [
  {
    id: 'centre',
    name: 'Own the centre',
    idea: 'The middle column sits on more fours than any other square on the board.',
    ask: 'Only one column keeps your win alive. Where do you play?',
    why: 'The middle. Every line worth having runs through it.',
    nudge: 'That gives the game back. Think about where the most fours meet.',
    close: 'And that is the middle. Fight for it early and half of your fours are already half-built.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Welcome. Before tactics, geometry. There are 69 different ways to make four in a row on this board — and 51 of them run through the middle column. Each outside column touches only 15.', cols: [3] },
      { grid: '000000000000000000000000000000000000000000', say: 'So the same disc is worth more in the middle than on the edge. Each of these two squares at the heart of the board sits on 13 possible fours. A corner sits on 3.', marks: [[2, 3], [3, 3]] },
      { grid: '000000000001010000201022020201211022211121', say: 'It decides whole games. From an empty board the opening move in the middle wins, and the same move in an outside column loses outright. Here, only the centre holds your win.' },
    ],
    drills: [
      { grid: '000000000001010000201022020201211022211121', good: [3], follow: false, show: [[2, 3]] },
      { grid: '000002001000100200020010021002001102121212', good: [3], follow: true, show: [[4, 2], [4, 6]] },
      { grid: '000000000000001000001120010221201211220212', good: [3], follow: false, show: [[3, 5]] },
    ],
  },
  {
    id: 'fork',
    name: 'Two threats at once',
    idea: 'One threat gets blocked. Two open threats in one move cannot both be stopped.',
    ask: 'Find the move that makes two threats at once.',
    why: 'Two open winning squares. They block one, you take the other.',
    nudge: 'That makes at most one threat — they simply block it and you are back where you started.',
    close: 'The fork is the engine of this game. Every other idea I teach you is a way of building one.',
    lesson: [
      { grid: '100010020202001210200222010011212011211221', say: 'A threat is an empty square that would give you four. Hold that word — everything else is built on it. A single threat is polite: they just fill the square.' },
      { grid: '100010020202001210200222110011212011211221', say: 'Two threats, both reachable, made by one disc — that is a fork, and it is how nearly every game is really won. They can answer one of them. Not both.', marks: [[1, 1], [2, 3]] },
      { grid: '100010020202001210200222010011212011211221', say: 'Your turn. One move here makes two.' },
    ],
    drills: [
      { grid: '100010020202001210200222010011212011211221', good: [3], follow: true, show: [[1, 1], [2, 3]] },
      { grid: '000000000000000000210210111012022202121210', good: [2], follow: true, show: [[2, 0], [3, 2]] },
      { grid: '000000000000000200010020202011122101122121', good: [3], follow: true, show: [[3, 2], [3, 4]] },
    ],
  },
  {
    id: 'seven',
    name: 'The seven',
    idea: 'One disc finishing two different lines — three along a row, three down a diagonal.',
    ask: 'One move here builds a row and a diagonal at the same time. Find it.',
    why: 'A row and a diagonal from the same disc. That shape is the seven.',
    nudge: 'That points one way only. Look for the disc that finishes two different lines.',
    close: 'Look for sevens in your own games. Once you know the shape, you will find it everywhere.',
    lesson: [
      { grid: '100000010000012000002110022112212222121112', say: 'The best disc on the board is one that belongs to two lines at once. Drawn out it looks like a 7: three along a row, three running down a diagonal, meeting at the same piece.' },
      { grid: '100000010000012000002111022112212222121112', say: 'Look what it asks for. The row wants one square; the diagonal wants a different one. Two lines, one disc — a fork you can aim for from a long way off.', marks: [[2, 1], [3, 3]] },
      { grid: '100000010000012000002110022112212222121112', say: 'Now find it: the one move here that starts both lines at once.' },
    ],
    drills: [
      { grid: '100000010000012000002110022112212222121112', good: [2], follow: true, show: [[2, 1], [3, 3]] },
      { grid: '010000002002000100100022010001102222112112', good: [3], follow: true, show: [[2, 5], [4, 0]] },
      { grid: '000010000002000002101000110200212021022112', good: [2], follow: false, show: [[2, 1], [3, 1], [3, 5]] },
    ],
  },
  {
    id: 'tempo',
    name: 'Block and build',
    idea: 'A forced block need not be a wasted move — block with a disc that threatens back.',
    ask: 'They have four next move. Deal with it.',
    why: 'Forced, yes — but your block also builds. Now they are the ones answering you.',
    nudge: 'They complete four next move. Everything except that block loses on the spot.',
    close: 'Block, but never block emptily. A defence that threatens back is not a defence — it is an attack.',
    lesson: [
      { grid: '001000000200001010002121010122202021122121', say: 'Now the other side of it. They are one move from four, and the square they need is marked. You have no choice: it has to be yours.', marks: [[4, 3]] },
      { grid: '001000000200001010002121010122212021122121', say: 'But a forced move is still a move. This block also gives you a three of your own — so the next question is theirs to answer, not yours. That is tempo: how a defence turns into an attack.', marks: [[2, 1]] },
      { grid: '001000000200001010002121010122202021122121', say: 'Block it. Then look at what your disc did on the way.' },
    ],
    drills: [
      { grid: '001000000200001010002121010122202021122121', good: [3], follow: false, show: [[2, 1]] },
      { grid: '000000021000001210000212000012101002122102', good: [3], follow: false, show: [[4, 5]] },
      { grid: '000000000000000002000110120012011002122200', good: [5], follow: false, show: [[2, 2]] },
    ],
  },
  {
    id: 'poison',
    name: 'Poisoned squares',
    idea: 'A disc under one of their winning squares lifts them straight onto it.',
    ask: 'Most of these columns hand them the win. Find the one move that keeps you alive.',
    why: 'Safe. The rest fill the square under a winning square of theirs — or lose a step later.',
    nudge: 'Look at what sits directly above each landing square. A disc of yours underneath their winning square hands them the game.',
    close: 'Before every drop, ask what square you are handing over. Two seconds of counting saves whole games.',
    lesson: [
      { grid: '110020021001022201102210220112021111221212', say: 'Before you look for your own move, find their winning squares — the empty ones that would give them four. These.', marks: [[2, 5], [3, 2]] },
      { grid: '110020021001022201102210220112021111221212', say: 'Now count what a drop underneath one does. Your disc does not just sit there; it raises them onto the square above. Every column marked here is poisoned.', cols: [2, 5] },
      { grid: '110020021001022201102210220112021111221212', say: 'So most of this board is a trap. One move keeps you alive. Only one.' },
    ],
    drills: [
      { grid: '110020021001022201102210220112021111221212', good: [3], follow: false, show: [[1, 2], [2, 2], [3, 5]] },
      { grid: '002100000122000011102102210122122022111201', good: [0], follow: true, show: [[3, 1]] },
      { grid: '020000201000010222001021100112121022122101', good: [2], follow: false, show: [] },
    ],
  },
  {
    id: 'stack',
    name: 'Stack your threats',
    idea: 'Two of your winning squares in one column, one directly above the other.',
    ask: 'Find the move that puts two of your winning squares in the same column, one above the other.',
    why: 'Stacked. Block the low square and their own disc carries you up to the high one.',
    nudge: 'Not that. Look for the column where two of your threats can sit on top of each other.',
    close: 'Two threats in one column, and their own move carries you to the win. Nothing here is prettier.',
    lesson: [
      { grid: '000000001110000221002011220222121212112211', say: 'This is the prettiest idea in the game, and it wins games on its own. Put two of your winning squares in the same column, one directly on top of the other.' },
      { grid: '000000001110000221002011221222121212112211', say: 'Count their options. They cannot block the low square without playing it — and that lifts you onto the high one. Block below, lose above. Leave it alone, and you simply take the low square.', marks: [[1, 4], [2, 4]] },
      { grid: '000000001110000221002011220222121212112211', say: 'Find the move that stacks them.' },
    ],
    drills: [
      { grid: '000000001110000221002011220222121212112211', good: [5], follow: true, show: [[1, 4], [2, 4]] },
      { grid: '000000000000100100220020012011001202212112', good: [3], follow: true, show: [[3, 2], [4, 2]] },
      { grid: '000001000000200000010002001200101122210122', good: [6], follow: true, show: [[4, 3], [5, 3]] },
    ],
  },
  {
    id: 'parity',
    name: 'Odd rows are yours',
    idea: 'Rows fill in order, so a threat on the right row is the one that gets collected.',
    ask: 'Two moves look alike here. Only the one whose threat lands on the right row wins. Find it.',
    why: 'That one. Your winning square sits on an odd row, so the filling arrives in your favour.',
    nudge: 'That threat sits on the wrong row — they get to fill that square, not you.',
    close: 'Counting rows is dull, and it wins games. Start counting around move ten and you will feel it.',
    lesson: [
      { grid: '000000000000000000000000000000000000000000', say: 'Count the rows from the bottom: 1, 2, 3, 4, 5, 6. Discs stack in that order and never out of it, and the board holds 42 squares — an even number.', rows: [5, 3, 1] },
      { grid: '000000000000000000000000000000000000000000', say: 'That splits the board between you. You opened this game, so the odd rows — 1, 3 and 5, lit up here — tend to fall to you, and the even rows to your opponent.', rows: [5, 3, 1] },
      { grid: '201001010200202010010101021012201202210221', say: 'So when both sides run out of safe moves, whoever\'s threat sits on the right row is the one who gets to fill it. Here, two moves look alike and only one is on your row.' },
    ],
    drills: [
      { grid: '201001010200202010010101021012201202210221', good: [1], follow: false, show: [[1, 3], [3, 3]] },
      { grid: '001000002100000110010012002021200202212121', good: [3], follow: false, show: [[3, 4]] },
      { grid: '100000020000001000000202000010101001220221', good: [3], follow: false, show: [[3, 1]] },
    ],
  },
  {
    id: 'defuse',
    name: 'Kill the fork early',
    idea: 'Everything you have learned, they can use. Take the double threat away a move early.',
    ask: 'They are one move from a double threat. Take it away.',
    why: 'Defused. The square their fork needed is yours.',
    nudge: 'Too slow — they play the fork, and two open threats cannot both be blocked.',
    close: 'That is the craft, then: build your own fork, and see theirs coming. Go and play.',
    lesson: [
      { grid: '000000200020020001001002200212112112111212', say: 'Last idea, and it is the one that keeps you alive. Every tactic I have shown you, your opponent can play too. So before you choose, ask what their next move does.' },
      { grid: '000000200020020001001002200212112112111212', say: 'If they reach the marked column they make two threats at once, and you have already seen how that ends. The move is not yours to find — it is theirs to lose.', marks: [[3, 1], [3, 4]] },
      { grid: '000000200020020001001002200212112112111212', say: 'Take it away from them.' },
    ],
    drills: [
      { grid: '000000200020020001001002200212112112111212', good: [4], follow: false, show: [[1, 2], [2, 5]] },
      { grid: '020000001100000210000112220021212001121122', good: [3], follow: false, show: [] },
      { grid: '000000002000000100000020200111211022211221', good: [2], follow: false, show: [[1, 0]] },
    ],
  },
];
